Holder manual
2729StormRobotics/StormRobotics2020 pull request #82
Opened 2020-02-12 22:38 UTC by irinale629823

created a command for manual control of the holder motor

2020-02-12 22:50 UTC, PKuppili commented on src/main/java/frc/robot/commands/HolderMotorManual.java
> +  }
This should be in execute()

2020-02-12 22:51 UTC, PKuppili requested changes
Please address the comment and fix the necessary code.

2020-02-13 20:52 UTC, irinale629823 commented on src/main/java/frc/robot/commands/HolderMotorManual.java
> +  }
i moved the code to execute()

2020-02-13 20:59 UTC, PKuppili approved these changes
Looks good!

2020-02-13 20:59 UTC, merged